version: '2'
services:
  redis:
    image: redis:2
    ports:
        - "6379"
    volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
        - .stack/data:/data
  watchmen-web:
    image: gcr.geekup.vn/tools/watchmen-web:latest
    build:
      context: ./
      dockerfile: Dockerfile-web-server
    ports:
        - "3000:3000"
    links:
        - redis
    env_file: docker-compose.env
  watchmen-monitor:
    image: gcr.geekup.vn/tools/watchmen-monitor:latest
    build:
      context: ./
      dockerfile: Dockerfile-monitor-server
    links:
        - redis
    env_file: docker-compose.env
