FROM node:alpine

WORKDIR /watchmen

# Add all the project
ADD . /watchmen
RUN rm -rf /watchmen/.git
RUN rm -rf /watchmen/screenshots


ENV WATCHMEN_WEB_PORT=3000

EXPOSE 3000

CMD ["usr/local/bin/node", 'run-web-server.js']