version: '2'
services:
  redis:
    image: redis:2
    ports:
        - "6379"
    volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
        - .stack/data:/data
  watchmenweb:
    build:
      context: ./
      dockerfile: Dockerfile-web-server
    ports:
        - "3000:3000"
    links:
        - redis
    env_file: docker-compose.env
  watchmenserver:
    build:
      context: ./
      dockerfile: Dockerfile-monitor-server
    links:
        - redis
    env_file: docker-compose.env
