version: '2'
services:
  redis:
    image: redis:2
    ports:
        - "6379"
    volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
        - .stack/data:/data
  watchmen-web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
        - "80:3000"
    links:
        - redis
    env_file: docker-compose.env
    volumes:
        - ./:/watchmen
    command: "nodemon -L run-web-server.js"

  watchmen-monitor:
    build:
      context: ./
      dockerfile: Dockerfile
    links:
        - redis
    env_file: docker-compose.env
    volumes:
        - ./:/watchmen
    command: "nodemon -L run-monitor-server.js"
